language: python
python:
  - "3.7"

branch: gh-pages

install:
  - pip install -r requirements.txt

script:
  - bash ./sean_corona.sh

deploy:
  provider: pages
  email : sean.davey@tieto.com
  name: 'Sean Davey'
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: gh-pages